---
name: Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]  # macOS-latest, windows-latest
        version: [18, 20, 22]

    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Install xmp to render mod
        run: sudo apt install xmp

      - name: Install Node deps
        run: npm i

      - name: Run the tests
        run: npm run test
